name: Lighthouse
on:
  workflow_call:
    inputs:
      PROJECT_DIR:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      NODE_CACHE_TYPE:
        required: true
        type: string
      NODE_CACHE_DEP_PATH:
        required: true
        type: string
    secrets:
      CYPRESS_BASE_URL:
        required: true
        type: string
      CYPRESS_BASIC_USERNAME:
        required: true
      CYPRESS_BASIC_PASSWORD:
        required: true
      LHCI_GITHUB_APP_TOKEN:
        required: true
      LHCI_TOKEN:
        required: true
      LHCI_DASHBOARD_URL:
        required: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.NODE_CACHE_TYPE }}
          cache-dependency-path: ${{ inputs.NODE_CACHE_DEP_PATH }}
      - name: Tests
        run: |
          cd ${{ inputs.PROJECT_DIR }}
          yarn
          npx @lhci/cli@0.9.x autorun --config=./lighthouserc.js
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_BASIC_USERNAME: ${{ secrets.CYPRESS_BASIC_USERNAME }}
          CYPRESS_BASIC_PASSWORD: ${{ secrets.CYPRESS_BASIC_PASSWORD }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_DASHBOARD_URL: ${{ secrets.LHCI_DASHBOARD_URL }}
