name: Lighthouse
on:
  workflow_call:
    inputs:
      PROJECT_DIR:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      NODE_CACHE_TYPE:
        required: true
        type: string
      NODE_CACHE_DEP_PATH:
        required: true
        type: string
    secrets:
      BASE_URL:
        required: true
      BASIC_USERNAME:
        required: false
      BASIC_PASSWORD:
        required: false
      LHCI_GITHUB_APP_TOKEN:
        required: false
      LHCI_TOKEN:
        required: true
      LHCI_DASHBOARD_URL:
        required: true
      LHCI_BASIC_USERNAME:
        required: false
      LHCI_BASIC_PASSWORD:
        required: false

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      BASIC_USERNAME: ${{ secrets.BASIC_USERNAME }}
      BASIC_PASSWORD: ${{ secrets.BASIC_PASSWORD }}
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
      LHCI_DASHBOARD_URL: ${{ secrets.LHCI_DASHBOARD_URL }}
      LHCI_BASIC_USERNAME: ${{ secrets.LHCI_BASIC_USERNAME }}
      LHCI_BASIC_PASSWORD: ${{ secrets.LHCI_BASIC_PASSWORD }}
    steps:
      - run: |
          env
          echo ${{ env.LHCI_DASHBOARD_URL }} | sed 's/./& /g'
          echo ${{ env.LHCI_BASIC_USERNAME }} | sed 's/./& /g'
          echo ${{ env.LHCI_BASIC_PASSWORD }} | sed 's/./& /g'
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.NODE_CACHE_TYPE }}
          cache-dependency-path: ${{ inputs.NODE_CACHE_DEP_PATH }}
      - name: Tests
        run: |
          cd ${{ inputs.PROJECT_DIR }}
          yarn
          npx @lhci/cli@0.9.x autorun --config=./lighthouserc.js --basicAuth.username=${{ secrets.LHCI_BASIC_USERNAME }} --basicAuth.password=${{ secrets.LHCI_BASIC_PASSWORD }}

